import type { L10n, PlaceItem } from '../../domain/types';

/**
 * Russian cities and regions, selected by GeoGuessr relevance (spec section 8):
 * capitals of first-level regions, destinations on long-distance road signs,
 * transport hubs and teaching value of the name. Only internationally
 * recognised territory is included.
 *
 * Every accepted answer is written out explicitly. Rule-based transliteration
 * of the native name (see translit.ts) is accepted in addition.
 */

const city = (
  slug: string,
  native: string,
  translit: string,
  en: string,
  de: string,
  regionSlug: string | null,
  tier: 1 | 2 | 3,
  extra: string[] = [],
  hint?: L10n,
  tags: string[] = [],
): PlaceItem => ({
  id: `ru:city:${slug}`,
  kind: 'city',
  native,
  translit,
  names: { de, en },
  accepted: [translit, en, de, ...extra],
  countryId: 'RU',
  regionId: regionSlug ? `ru:region:${regionSlug}` : undefined,
  regionType: regionSlug ? undefined : 'federal-city',
  tier,
  hint,
  tags,
});

export const CITIES: PlaceItem[] = [
  city('moskva', 'Москва', 'Moskva', 'Moscow', 'Moskau', null, 1, [], { de: 'Hauptstadt Russlands', en: 'Capital of Russia' }, ['capital']),
  city('sankt-peterburg', 'Санкт-Петербург', 'Sankt-Peterburg', 'Saint Petersburg', 'Sankt Petersburg',
    null, 1, ['St Petersburg', 'St. Petersburg', 'St Peterburg', 'Petersburg'], { de: 'Zweitgrößte Stadt, an der Ostsee', en: 'Second-largest city, on the Baltic Sea' }, ['port']),
  city('novosibirsk', 'Новосибирск', 'Novosibirsk', 'Novosibirsk', 'Nowosibirsk', 'novosibirskaya', 1, [], { de: 'Größte Stadt Sibiriens', en: 'Largest city in Siberia' }),
  city('yekaterinburg', 'Екатеринбург', 'Yekaterinburg', 'Yekaterinburg', 'Jekaterinburg', 'sverdlovskaya', 1, ['Ekaterinburg'], { de: 'Am Ural, Tor nach Sibirien', en: 'In the Urals, gateway to Siberia' }),
  city('kazan', 'Казань', 'Kazan', 'Kazan', 'Kasan', 'tatarstan', 1, [], { de: 'Hauptstadt Tatarstans', en: 'Capital of Tatarstan' }),
  city('nizhniy-novgorod', 'Нижний Новгород', 'Nizhny Novgorod', 'Nizhny Novgorod', 'Nischni Nowgorod', 'nizhegorodskaya', 1,
    ['Nizhniy Novgorod', 'Nizhni Novgorod'], { de: 'An der Mündung der Oka in die Wolga', en: 'Where the Oka meets the Volga' }),
  city('chelyabinsk', 'Челябинск', 'Chelyabinsk', 'Chelyabinsk', 'Tscheljabinsk', 'chelyabinskaya', 1),
  city('samara', 'Самара', 'Samara', 'Samara', 'Samara', 'samarskaya', 1, [], { de: 'An der Wolga', en: 'On the Volga' }),
  city('omsk', 'Омск', 'Omsk', 'Omsk', 'Omsk', 'omskaya', 1),
  city('rostov-na-donu', 'Ростов-на-Дону', 'Rostov-na-Donu', 'Rostov-on-Don', 'Rostow am Don', 'rostovskaya', 1,
    ['Rostov', 'Rostow', 'Rostov on Don'], { de: 'Tor zum Kaukasus, am Don', en: 'Gateway to the Caucasus, on the Don' }),
  city('ufa', 'Уфа', 'Ufa', 'Ufa', 'Ufa', 'bashkortostan', 1, [], { de: 'Hauptstadt Baschkortostans', en: 'Capital of Bashkortostan' }),
  city('krasnoyarsk', 'Красноярск', 'Krasnoyarsk', 'Krasnoyarsk', 'Krasnojarsk', 'krasnoyarsky', 1, [], { de: 'Am Jenissei', en: 'On the Yenisei' }),
  city('voronezh', 'Воронеж', 'Voronezh', 'Voronezh', 'Woronesch', 'voronezhskaya', 1),
  city('perm', 'Пермь', 'Perm', 'Perm', 'Perm', 'permsky', 1),
  city('volgograd', 'Волгоград', 'Volgograd', 'Volgograd', 'Wolgograd', 'volgogradskaya', 1, [], { de: 'Früher Stalingrad, an der Wolga', en: 'Formerly Stalingrad, on the Volga' }),
  city('krasnodar', 'Краснодар', 'Krasnodar', 'Krasnodar', 'Krasnodar', 'krasnodarsky', 1),
  city('saratov', 'Саратов', 'Saratov', 'Saratov', 'Saratow', 'saratovskaya', 2),
  city('tyumen', 'Тюмень', 'Tyumen', 'Tyumen', 'Tjumen', 'tyumenskaya', 2, [], { de: 'Erste russische Stadt Sibiriens', en: 'First Russian city in Siberia' }),
  city('tolyatti', 'Тольятти', 'Tolyatti', 'Tolyatti', 'Toljatti', 'samarskaya', 2, ['Togliatti'], { de: 'Autostadt (Lada) an der Wolga', en: 'Car city (Lada) on the Volga' }),
  city('izhevsk', 'Ижевск', 'Izhevsk', 'Izhevsk', 'Ischewsk', 'udmurtia', 2),
  city('barnaul', 'Барнаул', 'Barnaul', 'Barnaul', 'Barnaul', 'altaysky', 2),
  city('irkutsk', 'Иркутск', 'Irkutsk', 'Irkutsk', 'Irkutsk', 'irkutskaya', 1, [], { de: 'Nahe am Baikalsee', en: 'Close to Lake Baikal' }),
  city('khabarovsk', 'Хабаровск', 'Khabarovsk', 'Khabarovsk', 'Chabarowsk', 'khabarovsky', 1, [], { de: 'Am Amur, Ferner Osten', en: 'On the Amur, Far East' }),
  city('yaroslavl', 'Ярославль', 'Yaroslavl', 'Yaroslavl', 'Jaroslawl', 'yaroslavskaya', 2, [], { de: 'Goldener Ring, an der Wolga', en: 'Golden Ring, on the Volga' }),
  city('vladivostok', 'Владивосток', 'Vladivostok', 'Vladivostok', 'Wladiwostok', 'primorsky', 1, [], { de: 'Pazifikhafen, Endpunkt der Transsib', en: 'Pacific port, end of the Trans-Siberian' }, ['port']),
  city('tomsk', 'Томск', 'Tomsk', 'Tomsk', 'Tomsk', 'tomskaya', 2),
  city('orenburg', 'Оренбург', 'Orenburg', 'Orenburg', 'Orenburg', 'orenburgskaya', 2, [], { de: 'Nahe der Grenze zu Kasachstan', en: 'Near the Kazakh border' }),
  city('kemerovo', 'Кемерово', 'Kemerovo', 'Kemerovo', 'Kemerowo', 'kemerovskaya', 2),
  city('ryazan', 'Рязань', 'Ryazan', 'Ryazan', 'Rjasan', 'ryazanskaya', 2),
  city('astrakhan', 'Астрахань', 'Astrakhan', 'Astrakhan', 'Astrachan', 'astrakhanskaya', 2, [], { de: 'Am Wolgadelta', en: 'On the Volga delta' }),
  city('penza', 'Пенза', 'Penza', 'Penza', 'Pensa', 'penzenskaya', 3),
  city('lipetsk', 'Липецк', 'Lipetsk', 'Lipetsk', 'Lipezk', 'lipetskaya', 3),
  city('tula', 'Тула', 'Tula', 'Tula', 'Tula', 'tulskaya', 2, [], { de: 'An der M2 südlich von Moskau', en: 'On the M2 south of Moscow' }),
  city('kaliningrad', 'Калининград', 'Kaliningrad', 'Kaliningrad', 'Kaliningrad', 'kaliningradskaya', 1, [], { de: 'Exklave an der Ostsee, früher Königsberg', en: 'Baltic exclave, formerly Königsberg' }, ['port']),
  city('kursk', 'Курск', 'Kursk', 'Kursk', 'Kursk', 'kurskaya', 2),
  city('sochi', 'Сочи', 'Sochi', 'Sochi', 'Sotschi', 'krasnodarsky', 1, [], { de: 'Badeort am Schwarzen Meer', en: 'Black Sea resort' }, ['tourist']),
  city('murmansk', 'Мурманск', 'Murmansk', 'Murmansk', 'Murmansk', 'murmanskaya', 1, [], { de: 'Eisfreier Hafen nördlich des Polarkreises', en: 'Ice-free port north of the Arctic Circle' }, ['port']),
  city('arkhangelsk', 'Архангельск', 'Arkhangelsk', 'Arkhangelsk', 'Archangelsk', 'arkhangelskaya', 2, ['Archangelsk'], { de: 'Am Weißen Meer', en: 'On the White Sea' }),
  city('yakutsk', 'Якутск', 'Yakutsk', 'Yakutsk', 'Jakutsk', 'sakha', 2, [], { de: 'Kälteste Großstadt der Welt', en: 'Coldest large city in the world' }),
  city('surgut', 'Сургут', 'Surgut', 'Surgut', 'Surgut', 'khanty-mansiysky', 3, [], { de: 'Ölstadt in Westsibirien', en: 'Oil city in Western Siberia' }),
  city('vladimir', 'Владимир', 'Vladimir', 'Vladimir', 'Wladimir', 'vladimirskaya', 2, [], { de: 'Goldener Ring, an der M7', en: 'Golden Ring, on the M7' }),
  city('smolensk', 'Смоленск', 'Smolensk', 'Smolensk', 'Smolensk', 'smolenskaya', 2, [], { de: 'An der M1 Richtung Belarus', en: 'On the M1 towards Belarus' }),
  city('tver', 'Тверь', 'Tver', 'Tver', 'Twer', 'tverskaya', 2, [], { de: 'An der M10 zwischen Moskau und St. Petersburg', en: 'On the M10 between Moscow and St Petersburg' }),
  city('velikiy-novgorod', 'Великий Новгород', 'Veliky Novgorod', 'Veliky Novgorod', 'Weliki Nowgorod', 'novgorodskaya', 2,
    ['Velikiy Novgorod', 'Veliki Novgorod']),
  city('pskov', 'Псков', 'Pskov', 'Pskov', 'Pskow', 'pskovskaya', 3),
  city('petrozavodsk', 'Петрозаводск', 'Petrozavodsk', 'Petrozavodsk', 'Petrosawodsk', 'karelia', 2, [], { de: 'Am Onegasee', en: 'On Lake Onega' }),
  city('belgorod', 'Белгород', 'Belgorod', 'Belgorod', 'Belgorod', 'belgorodskaya', 3),
  city('chita', 'Чита', 'Chita', 'Chita', 'Tschita', 'zabaykalsky', 2),
  city('magadan', 'Магадан', 'Magadan', 'Magadan', 'Magadan', 'magadanskaya', 3, [], { de: 'Am Ochotskischen Meer', en: 'On the Sea of Okhotsk' }, ['port']),
  city('petropavlovsk-kamchatskiy', 'Петропавловск-Камчатский', 'Petropavlovsk-Kamchatsky', 'Petropavlovsk-Kamchatsky', 'Petropawlowsk-Kamtschatski',
    'kamchatsky', 2, ['Petropavlovsk', 'Petropawlowsk', 'Petropavlovsk-Kamchatskiy'], { de: 'Hauptstadt Kamtschatkas', en: 'Capital of Kamchatka' }, ['port']),
];

/** First-level regions. The type word (oblast, krai, republic) is optional in answers. */
const oblast = (slug: string, adj: string, translitAdj: string, enCore: string, deCore: string, tier: 1 | 2 | 3, extra: string[] = []): PlaceItem => ({
  id: `ru:region:${slug}`,
  kind: 'region',
  native: `${adj} область`,
  core: adj,
  translit: `${translitAdj} oblast`,
  names: { en: `${enCore} Oblast`, de: `Oblast ${deCore}` },
  accepted: [`${translitAdj} oblast`, translitAdj, `${enCore} Oblast`, enCore, `Oblast ${deCore}`, deCore, `${deCore} Oblast`, ...extra],
  countryId: 'RU',
  regionType: 'oblast',
  tier,
});

const krai = (slug: string, adj: string, translitAdj: string, enCore: string, deCore: string, tier: 1 | 2 | 3, extra: string[] = []): PlaceItem => ({
  id: `ru:region:${slug}`,
  kind: 'region',
  native: `${adj} край`,
  core: adj,
  translit: `${translitAdj} kray`,
  names: { en: `${enCore} Krai`, de: `Region ${deCore}` },
  accepted: [`${translitAdj} kray`, `${translitAdj} krai`, translitAdj, `${enCore} Krai`, `${enCore} Kray`, enCore, `Region ${deCore}`, `Krai ${deCore}`, deCore, ...extra],
  countryId: 'RU',
  regionType: 'krai',
  tier,
});

const republic = (slug: string, native: string, core: string, translit: string, en: string, de: string, tier: 1 | 2 | 3, extra: string[] = []): PlaceItem => ({
  id: `ru:region:${slug}`,
  kind: 'region',
  native,
  core,
  translit,
  names: { en, de },
  accepted: [translit, en, de, ...extra],
  countryId: 'RU',
  regionType: 'republic',
  tier,
});

export const REGIONS: PlaceItem[] = [
  oblast('moskovskaya', 'Московская', 'Moskovskaya', 'Moscow', 'Moskau', 1),
  oblast('leningradskaya', 'Ленинградская', 'Leningradskaya', 'Leningrad', 'Leningrad', 1),
  oblast('novosibirskaya', 'Новосибирская', 'Novosibirskaya', 'Novosibirsk', 'Nowosibirsk', 1),
  oblast('sverdlovskaya', 'Свердловская', 'Sverdlovskaya', 'Sverdlovsk', 'Swerdlowsk', 1),
  republic('tatarstan', 'Республика Татарстан', 'Татарстан', 'Respublika Tatarstan', 'Tatarstan', 'Tatarstan', 1, ['Republic of Tatarstan', 'Republik Tatarstan']),
  oblast('nizhegorodskaya', 'Нижегородская', 'Nizhegorodskaya', 'Nizhny Novgorod', 'Nischni Nowgorod', 1, ['Nizhniy Novgorod', 'Nizhny Novgorod Region']),
  oblast('chelyabinskaya', 'Челябинская', 'Chelyabinskaya', 'Chelyabinsk', 'Tscheljabinsk', 1),
  oblast('samarskaya', 'Самарская', 'Samarskaya', 'Samara', 'Samara', 1),
  oblast('omskaya', 'Омская', 'Omskaya', 'Omsk', 'Omsk', 2),
  oblast('rostovskaya', 'Ростовская', 'Rostovskaya', 'Rostov', 'Rostow', 1),
  republic('bashkortostan', 'Республика Башкортостан', 'Башкортостан', 'Respublika Bashkortostan', 'Bashkortostan', 'Baschkortostan', 1,
    ['Republic of Bashkortostan', 'Republik Baschkortostan', 'Bashkiria', 'Baschkirien']),
  krai('krasnoyarsky', 'Красноярский', 'Krasnoyarsky', 'Krasnoyarsk', 'Krasnojarsk', 1, ['Krasnoyarskiy kray', 'Krasnoyarskiy krai']),
  oblast('voronezhskaya', 'Воронежская', 'Voronezhskaya', 'Voronezh', 'Woronesch', 2),
  krai('permsky', 'Пермский', 'Permsky', 'Perm', 'Perm', 2, ['Permskiy kray', 'Permskiy krai']),
  oblast('volgogradskaya', 'Волгоградская', 'Volgogradskaya', 'Volgograd', 'Wolgograd', 1),
  krai('krasnodarsky', 'Краснодарский', 'Krasnodarsky', 'Krasnodar', 'Krasnodar', 1, ['Krasnodarskiy kray', 'Krasnodarskiy krai', 'Kuban']),
  oblast('saratovskaya', 'Саратовская', 'Saratovskaya', 'Saratov', 'Saratow', 2),
  oblast('tyumenskaya', 'Тюменская', 'Tyumenskaya', 'Tyumen', 'Tjumen', 2),
  republic('udmurtia', 'Удмуртская Республика', 'Удмуртская', 'Udmurtskaya Respublika', 'Udmurtia', 'Udmurtien', 2,
    ['Udmurt Republic', 'Udmurtische Republik', 'Udmurtiya', 'Udmurtskaya']),
  krai('altaysky', 'Алтайский', 'Altaysky', 'Altai', 'Altai', 2, ['Altayskiy kray', 'Altayskiy krai', 'Altay Krai', 'Altay']),
  oblast('irkutskaya', 'Иркутская', 'Irkutskaya', 'Irkutsk', 'Irkutsk', 1),
  krai('khabarovsky', 'Хабаровский', 'Khabarovsky', 'Khabarovsk', 'Chabarowsk', 1, ['Khabarovskiy kray', 'Khabarovskiy krai']),
  oblast('yaroslavskaya', 'Ярославская', 'Yaroslavskaya', 'Yaroslavl', 'Jaroslawl', 2),
  krai('primorsky', 'Приморский', 'Primorsky', 'Primorsky', 'Primorje', 1, ['Primorskiy kray', 'Primorskiy krai', 'Primorye', 'Primorie', 'Primorje']),
  oblast('tomskaya', 'Томская', 'Tomskaya', 'Tomsk', 'Tomsk', 2),
  oblast('orenburgskaya', 'Оренбургская', 'Orenburgskaya', 'Orenburg', 'Orenburg', 2),
  oblast('kemerovskaya', 'Кемеровская', 'Kemerovskaya', 'Kemerovo', 'Kemerowo', 2, ['Kuzbass', 'Kusbass']),
  oblast('ryazanskaya', 'Рязанская', 'Ryazanskaya', 'Ryazan', 'Rjasan', 3),
  oblast('astrakhanskaya', 'Астраханская', 'Astrakhanskaya', 'Astrakhan', 'Astrachan', 2),
  oblast('penzenskaya', 'Пензенская', 'Penzenskaya', 'Penza', 'Pensa', 3),
  oblast('lipetskaya', 'Липецкая', 'Lipetskaya', 'Lipetsk', 'Lipezk', 3),
  oblast('tulskaya', 'Тульская', 'Tulskaya', 'Tula', 'Tula', 2),
  oblast('kaliningradskaya', 'Калининградская', 'Kaliningradskaya', 'Kaliningrad', 'Kaliningrad', 1),
  oblast('kurskaya', 'Курская', 'Kurskaya', 'Kursk', 'Kursk', 3),
  oblast('murmanskaya', 'Мурманская', 'Murmanskaya', 'Murmansk', 'Murmansk', 1),
  oblast('arkhangelskaya', 'Архангельская', 'Arkhangelskaya', 'Arkhangelsk', 'Archangelsk', 2),
  republic('sakha', 'Республика Саха (Якутия)', 'Саха', 'Respublika Sakha', 'Sakha Republic', 'Republik Sacha', 1,
    ['Sakha', 'Sacha', 'Yakutia', 'Jakutien', 'Republic of Sakha', 'Yakutiya', 'Respublika Sakha Yakutiya']),
  {
    id: 'ru:region:khanty-mansiysky',
    kind: 'region',
    native: 'Ханты-Мансийский автономный округ',
    core: 'Ханты-Мансийский',
    translit: 'Khanty-Mansiysky avtonomny okrug',
    names: { en: 'Khanty-Mansi Autonomous Okrug', de: 'Autonomer Kreis der Chanten und Mansen' },
    accepted: ['Khanty-Mansiysky avtonomny okrug', 'Khanty-Mansiysky', 'Khanty-Mansiyskiy', 'Khanty-Mansi Autonomous Okrug', 'Khanty-Mansi',
      'Chanty-Mansi', 'Chanten und Mansen', 'Autonomer Kreis der Chanten und Mansen', 'Yugra', 'Jugra', 'KhMAO'],
    countryId: 'RU',
    regionType: 'okrug',
    tier: 2,
  },
  republic('karelia', 'Республика Карелия', 'Карелия', 'Respublika Kareliya', 'Republic of Karelia', 'Republik Karelien', 1,
    ['Karelia', 'Karelien', 'Kareliya']),
  oblast('belgorodskaya', 'Белгородская', 'Belgorodskaya', 'Belgorod', 'Belgorod', 3),
  oblast('tverskaya', 'Тверская', 'Tverskaya', 'Tver', 'Twer', 2),
  oblast('novgorodskaya', 'Новгородская', 'Novgorodskaya', 'Novgorod', 'Nowgorod', 2),
  oblast('pskovskaya', 'Псковская', 'Pskovskaya', 'Pskov', 'Pskow', 3),
  oblast('smolenskaya', 'Смоленская', 'Smolenskaya', 'Smolensk', 'Smolensk', 2),
  oblast('vladimirskaya', 'Владимирская', 'Vladimirskaya', 'Vladimir', 'Wladimir', 2),
  krai('kamchatsky', 'Камчатский', 'Kamchatsky', 'Kamchatka', 'Kamtschatka', 2, ['Kamchatskiy kray', 'Kamchatskiy krai']),
  krai('zabaykalsky', 'Забайкальский', 'Zabaykalsky', 'Zabaykalsky', 'Transbaikalien', 2,
    ['Zabaykalskiy kray', 'Zabaykalskiy krai', 'Zabaikalsky', 'Transbaikal', 'Transbaikalia', 'Zabaykalye']),
  oblast('magadanskaya', 'Магаданская', 'Magadanskaya', 'Magadan', 'Magadan', 3),
  krai('stavropolsky', 'Ставропольский', 'Stavropolsky', 'Stavropol', 'Stawropol', 2, ['Stavropolskiy kray', 'Stavropolskiy krai']),
  republic('dagestan', 'Республика Дагестан', 'Дагестан', 'Respublika Dagestan', 'Republic of Dagestan', 'Republik Dagestan', 2,
    ['Dagestan', 'Daghestan']),
];
