/**
 * App und offline: the service worker is generated at build time (see the
 * `sylareadsPwa` plugin in vite.config.ts). This module has no browser or
 * Node dependencies so the build and the tests can both use it.
 *
 * Strategy
 * - Install: every file of the build is downloaded once (precache), except the
 *   Firebase chunks (only signed-in players need them) and old .woff fonts
 *   (every browser that runs a service worker reads .woff2).
 * - Requests: answered from the cache first; anything else from this site is
 *   fetched and kept (that is how the Firebase chunks become available offline).
 * - Page loads always get the cached index.html of the active version, so page
 *   and files never mix two versions.
 * - A new version waits until the player taps "Neu laden"; then old caches go.
 */

export interface BuiltFile {
  /** Path relative to the site root, e.g. "assets/index-abc.js". */
  name: string;
  /** Part of the Firebase SDK. */
  firebase?: boolean;
}

export const SW_FILE = 'sw.js';
const CACHE_PREFIX = 'sylareads-';

/** Files to download at install, sorted and without duplicates. */
export function precacheList(files: BuiltFile[]): string[] {
  const keep = (f: BuiltFile) =>
    !f.firebase && f.name !== SW_FILE && !f.name.endsWith('.map') && !/\.woff$/.test(f.name) && !f.name.startsWith('.');
  return [...new Set(['index.html', ...files.filter(keep).map((f) => f.name)])].sort();
}

/** A short version id that changes whenever any file name changes (file names carry content hashes). */
export function cacheVersion(list: string[]): string {
  let h = 0x811c9dc5;
  for (const ch of list.join('\n')) {
    h ^= ch.codePointAt(0)!;
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h.toString(36);
}

/** The service worker's source code. */
export function serviceWorkerSource(list: string[], version: string): string {
  return `// Generated by vite.config.ts (src/pwa/serviceWorker.ts) – do not edit.
const VERSION = ${JSON.stringify(version)};
const PRECACHE = ${JSON.stringify(CACHE_PREFIX)} + VERSION;
const RUNTIME = ${JSON.stringify(CACHE_PREFIX + 'runtime')};
const FILES = ${JSON.stringify(list)};
const INDEX = new URL('index.html', self.registration.scope).href;

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(PRECACHE).then((cache) => cache.addAll(FILES.map((f) => new Request(new URL(f, self.registration.scope).href, { cache: 'reload' })))),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => {
        // After an update: drop the old version and the files kept at runtime (they belong to it).
        const old = keys.filter((k) => k.startsWith(${JSON.stringify(CACHE_PREFIX)}) && k !== PRECACHE && k !== RUNTIME);
        return Promise.all([...old, ...(old.length ? [RUNTIME] : [])].map((k) => caches.delete(k)));
      })
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'skip-waiting') self.skipWaiting();
  if (event.data && event.data.type === 'version' && event.ports[0]) event.ports[0].postMessage(VERSION);
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin || !url.href.startsWith(self.registration.scope)) return;
  if (url.pathname.endsWith('/${SW_FILE}')) return;
  if (req.mode === 'navigate' && (url.pathname.endsWith('/') || url.pathname.endsWith('/index.html'))) {
    event.respondWith(caches.match(INDEX, { cacheName: PRECACHE }).then((hit) => hit || fetch(req)));
    return;
  }
  event.respondWith(
    caches.match(req).then(
      (hit) =>
        hit ||
        fetch(req).then((res) => {
          if (res.ok && res.type === 'basic') {
            const copy = res.clone();
            caches.open(RUNTIME).then((cache) => cache.put(req, copy));
          }
          return res;
        }),
    ),
  );
});
`;
}
