// Copies only the font subsets the course „Schriften erkennen“ needs into
// src/features/scripts/fonts/ and writes fonts.css. Run after changing
// src/content/scripts/data.ts:  node tools/script-fonts.mjs
// (A test checks that every character of the course is covered.)
// The font packages are only needed for this step, so they are not in package.json:
//   npm i --no-save @fontsource/noto-sans-{arabic,hebrew,lao,khmer,devanagari,gurmukhi,gujarati,oriya,tamil,telugu,kannada,malayalam,sinhala,jp,tc,kr} @fontsource/noto-serif-tibetan
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const FONTS = {
  arabic: 'noto-sans-arabic', hebrew: 'noto-sans-hebrew', lao: 'noto-sans-lao', khmer: 'noto-sans-khmer',
  devanagari: 'noto-sans-devanagari', gurmukhi: 'noto-sans-gurmukhi', gujarati: 'noto-sans-gujarati', oriya: 'noto-sans-oriya',
  tibetan: 'noto-serif-tibetan', tamil: 'noto-sans-tamil', telugu: 'noto-sans-telugu', kannada: 'noto-sans-kannada',
  malayalam: 'noto-sans-malayalam', sinhala: 'noto-sans-sinhala', jp: 'noto-sans-jp', tc: 'noto-sans-tc', kr: 'noto-sans-kr',
};
const SKIP = /-(latin|latin-ext|cyrillic|cyrillic-ext|greek|greek-ext|vietnamese|math|symbols)-400/;
const data = fs.readFileSync(path.join(root, 'src/content/scripts/data.ts'), 'utf8');
const used = new Set([...data].filter((c) => c.codePointAt(0) > 0x2ff).map((c) => c.codePointAt(0)));

const inRange = (cp, range) =>
  range.split(',').some((r) => {
    const [a, b] = r.trim().replace(/^U\+/, '').split('-');
    const lo = parseInt(a, 16);
    const hi = b ? parseInt(b, 16) : lo;
    return cp >= lo && cp <= hi;
  });

const outDir = path.join(root, 'src/features/scripts/fonts');
fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });
let css = '/* Generated by tools/script-fonts.mjs – only the subsets this course uses (Noto, SIL OFL 1.1). */\n';
let total = 0;
for (const pkg of Object.values(FONTS)) {
  const dir = path.join(root, 'node_modules/@fontsource', pkg);
  const src = fs.readFileSync(path.join(dir, '400.css'), 'utf8');
  for (const block of src.split('@font-face').slice(1)) {
    const file = /url\(\.\/files\/([^)]+\.woff2)\)/.exec(block)?.[1];
    const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1];
    const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
    if (!file || !range || !family || SKIP.test(file)) continue;
    if (![...used].some((cp) => inRange(cp, range))) continue;
    fs.copyFileSync(path.join(dir, 'files', file), path.join(outDir, file));
    total += fs.statSync(path.join(outDir, file)).size;
    css += `@font-face {\n  font-family: '${family}';\n  font-style: normal;\n  font-display: swap;\n  font-weight: 400;\n  src: url(./fonts/${file}) format('woff2');\n  unicode-range: ${range};\n}\n`;
  }
}
fs.writeFileSync(path.join(root, 'src/features/scripts/fonts.css'), css);
fs.copyFileSync(path.join(root, 'node_modules/@fontsource/noto-sans-jp/LICENSE'), path.join(outDir, 'OFL.txt'));
console.log(`${fs.readdirSync(outDir).length - 1} files, ${(total / 1024).toFixed(0)} KB`);
